### ISSUE TITLE
kerberos authentication?

### ISSUE THREAD

**Issue by jmartin-sul** [int128/groovy-ssh#141]
I'm new to using this project and JSch, so this might be a naive question, but would it be possible to allow SSH auth via kerberos?  e.g., by adding `gssapi-with-mic.krb5` to the list of `PreferredAuthentications` in [the JSch part of session setup](https://github.com/int128/groovy-ssh/blob/master/core/src/main/groovy/org/hidetake/groovy/ssh/connection/ConnectionManager.groovy#L109), e.g.:
```groovy
session.setConfig('PreferredAuthentications', 'publickey,keyboard-interactive,password,gssapi-with-mic.krb5')
```

or by just making the `'PreferredAuthentications'` config option settable via Groovy SSH settings?

Thanks...

**Comment by jmartin-sul** [comment]
I also just realized while looking at this again:  I filed this against groovy-ssh, because that's what the stack trace pointed to when I tried to connect to a kerberos authenticated server.  But I was actually doing that via gradle-ssh (since the intent is to use the Gradle SSH plugin to deploy a Java project that we're building using Gradle).

It seems that both projects are authored by the same person or organization, so I'll just ask in this ticket: is it the case that if this setting were added to groovy ssh, that the setting would also be available to configure in the gradle ssh plugin?  I'm happy to ask that question on the other project, if this is a bad place for it.

**Comment by jmartin-sul** [comment]
FWIW, our team might have a deployment solution that makes this a moot point for us (we might use an existing jenkins instance to build and deploy instead of a gradle task run from a developer machine).

**Comment by int128** [comment]
All right, feel free to open issues in either Groovy SSH or Gradle SSH Plugin.

JSch seems support Kerberos but I don't have environment to verify the behavior of authentication. So I will make `PreferredAuthentication` settable in the next release (planned in 2.2.0) and would you verify it?

**Comment by jmartin-sul** [comment]
that'd be great, thanks!  i can definitely do that.

**Comment by int128** [comment]
2.2.0 has been released. Would you try following settings on the new release?

```groovy
ssh.remotes {
  testServer {
    user = ...
    authentications = ['gssapi-with-mic.krb5']
  }
}
```

**Comment by jmartin-sul** [comment]
thanks, much appreciated!  i get a different error now (`Auth fail` instead of `Auth cancel`).  so, definitely works for picking up the setting, and tries to do something different than it did before, but still not quite working in my environment.  but this could well be my environment's configuration, and since we've started pursuing an alternate deployment approach, i won't be able to spend too much time investigating this.

regardless, thanks very much for the prompt response.  entirely possible we'll have a need to pursue this more in the future, and hopefully this change will be beneficial to others anyway.

**Comment by int128** [comment]
You're welcome. Please let me know if kerberos auth works well on your environment. It makes the plugin better.
