### ISSUE TITLE
Dependency on old agent proxy lib prevents use from multiple user accounts

### ISSUE THREAD

**Issue by gbehrmann** [int128/groovy-ssh#219]
The plugin depends on the JSch agent proxy lib version 0.0.7. That lib in turn depends on JNA version 3.4.0. JNA unpacks a library in the temporary folder `/tmp/jna`. This prevents the use if the library from multiple user accounts as the temporary directory is only writable to the first user.

Versions 0.0.8 and 0.0.9 of the agent proxy lib use newer versions of JNA that resolve this issue. A temporary workaround is to force a newer version of JNA:

```
buildscript {
    dependencies {
        classpath group: 'net.java.dev.jna', name: 'jna', version: '3.5.2'
    }
}
```

but it would be much preferred if groovy-ssh could upgrade to the newer version of the agent proxy library.

### Environment info

gradle-ssh-plugin-2.7.2 (groovy-ssh-2.7.2, jsch-0.1.53, groovy-2.4.7, java-1.8.0_74)

### Steps to reproduce
1.  Deploy as one user
2. Repeat deployment from a different user account on the same machine
3. The second deployment fails because step one creates `/tmp/jna` and the directory is only writable to the first account.

```
 Failed to create temporary file for jnidispatch library: java.io.IOException: Permission denied
```

**Comment by int128** [comment]
Thank you for the issue report. Fixed in 2.8.0 and please try it.
