### ISSUE TITLE
known_hosts not read properly for setting server_host_key

### ISSUE THREAD

**Issue by AarjavP** [int128/groovy-ssh#234]
Problem:
Given `known_hosts` with `server,127.0.0.1  ecdsa-sha2-nistp256 ...` and on the client side, we are connecting using the hostname `server`.
groovy-ssh cannot find an entry for `server`, as the entry in the hostname is treated as `server,127.0.0.1` instead of two different ones.
The `server_host_key` property is not set for Jsch, which may cause unexpected authentication errors.

Possible Fix:
Change [HostKeyRepository.compare(HostKey, host, port)](https://github.com/int128/groovy-ssh/blob/986e7a630dcc5a853df040f11878a5faf2dfdaec/core/src/main/groovy/org/hidetake/groovy/ssh/connection/HostKeyRepository.groovy#L58) to consider multiple hosts in given `HostKey` as well. 
unfortunately `Jsch`'s `HostKey.isMatched(host)` method is package private and i'm not sure if it is worth to call it using reflection or something similar.

**Comment by int128** [comment]
Merged.

**Comment by int128** [comment]
Thank you for your contribution.
