### ISSUE TITLE
groovy-ssh is incompatible with Groovy 2.5 and higher

### ISSUE THREAD

**Issue by cliffred** [int128/groovy-ssh#243]
### Environment info
Groovy 2.5 and higher

### Problem
Since Groovy 2.5 the implementations of DefaultGroovyMethods.push() and pop() changed. They push and pop to and from the beginning of the collection instead of to the end. Because of this change directoryStack in Stfp.groovy and RecursiveReceiver.groovy does not work in the same way: sub directories get prepended instead of appended resulting in multiple problems, e.g. SSH_FX_NO_SUCH_FILE.

**Comment by JamesXNelson** [comment]
hm, sure would be nice if @int128 could take a look.  ...or if someone else wanted to maintain and release updates.  Can't upgrade to gradle 5.X as it uses groovy 2.5.X...

**Comment by cliffred** [comment]
> hm, sure would be nice if @int128 could take a look. ...or if someone else wanted to maintain and release updates. Can't upgrade to gradle 5.X as it uses groovy 2.5.X...

Upgrading to Gradle 5 was also the way in which we encountered this problem. I've published my fork with the fix to our own artifact repository and that's what we're using now. It's not ideal, but this way we can use Gradle 5.

**Comment by int128** [comment]
groovy-ssh and gradle-ssh-plugin 2.10.1 should fix this.
