### ISSUE TITLE
org.hidetake:groovy-ssh:2.11.1 not available at Maven Central

### ISSUE THREAD

**Issue by stbstb** [int128/groovy-ssh#302]
and not on any other Maven repo I could find.

Prevents us from updating the Gradle plugin to 2.11.1.

**Comment by MrZeusTheCoder** [comment]
Hidetake is working to get it on Maven. See this issue: https://github.com/int128/gradle-ssh-plugin/issues/378. Unfortunately getting something on Maven Central is not so easy if you aren't approved already.

**Comment by int128** [comment]
I published groovy-ssh 2.11.2 to Maven Central, and Gradle SSH Plugin 2.11.2.
https://github.com/int128/gradle-ssh-plugin/issues/378#issuecomment-1449140301
