### ISSUE TITLE
SftpOperations and FileTransferLogger always log to slf4j

### ISSUE THREAD

**Issue by chilloutman** [int128/groovy-ssh#46]
When using `put`, log output always goes to SLF4J and never to `System.out`. Even when this is set:

``` groovy
ssh.settings { logging = 'stdout' }
```

all log entries related to the SFTP are still logged using the SLF4J logger.

**Comment by int128** [comment]
`logging` setting intends to control visibility of standard output and error stream in the command execution, not including SFTP.

**Comment by chilloutman** [comment]
Oh, I have misunderstood that feature.

Since I'm using `groovy-ssh` in a groovy command line script, I was hoping easily get rid of the fully qualified class names and such that are part of the LOG4J log format.

I'll make do with the `slf4j-simple`.

**Comment by int128** [comment]
Do you want to customize the log format? `groovy-ssh` is shipped with Logback but does not provide customizing at this moment. I will add it in the future release.

**Comment by chilloutman** [comment]
I use `groovy-ssh` it via [Grape](http://groovy.codehaus.org/Grape) inside a lightweight script, so simplifying the log output would be nice to have.

**Comment by int128** [comment]
1.1.3 is released now and I added Logback configuration API. If you use groovy-ssh with Logback on Grape, please try following code:
```groovy
logback level: 'INFO', pattern: '%msg%d'
```
Thanks for the idea.

**Comment by chilloutman** [comment]
That's fantastic!

Where would the `logback level: 'INFO', pattern: '%msg%d'` line go? There seems to be so such method in `ssh.settings`.

I only managed to get it to work by using `LogbackConfig.configureLogback()`:

```groovy
#!/usr/bin/env groovy

@Grab('org.hidetake:groovy-ssh:1.1.3')
@Grab('ch.qos.logback:logback-classic:1.1.2')
import org.hidetake.groovy.ssh.Ssh
import org.hidetake.groovy.ssh.LogbackConfig

LogbackConfig.configureLogback(level: 'INFO', pattern: '[groovy-ssh] %msg%n')
def ssh = Ssh.newService()

ssh.remotes {
  webServer {
    host = 'localhost'
    // ...
   }
}

// ...
```

It works nicely though, and makes `groovy-ssh` an even better alternative to shell scripts for ssh tasks.

**Comment by int128** [comment]
Oh, mistaken. It should use `LogbackConfig.configureLogback` in this situation.
Thanks.

**Comment by chilloutman** [comment]
`LogbackConfig.configureLogback` is no longer available in the current version. (2.0.0)

Is there a new / alternative way of configuring the log pattern?

**Comment by chilloutman** [comment]
Using `slf4j-simple` works well enough, actually.

If anyone wants to do something similar:

```
@Grab('org.hidetake:groovy-ssh:2.9.0')
@Grab('org.slf4j:slf4j-simple:1.7.25')
```
